# https://gist.github.com/gnarf/b103e77f37236ca72d8e
:vms:
  ntp-box1:
    :hostname: "ntp-box1"
    :ip: "192.168.50.106"
    :ram: 2048
    :cpu: 2
    :box: "ubuntu/xenial64"
    :id: 10

:groups:
  ntp-box1:
    - ntp-box1
  servers:
    - ntp-box1
  kubernetes-ntp-box1:
    - ntp-box1
  kubernetes:
    - ntp-box1
