---
# handlers file for boss-ansible-role-ntp

# - name: restart ntpd
#   service:
#     name: systemd-ntpd
#     state: restarted
# handlers file for ansible-ntp
- name: restart ntp
  service:
    name: "ntp"
    state: "restarted"
  become: true
  when: not ansible_check_mode

- name: restart ntpd
  service:
    name: "ntpd"
    state: "restarted"
  become: true
  when: not ansible_check_mode
